name: scap-workbench
adopt-info: scap-workbench
summary: A GUI tool for SCAP content
description: |
  SCAP Workbench is a GUI tool that provides scanning, tailoring and validation functionality 
  for SCAP content. It uses openscap library to access SCAP functionalities.
  
  Homepage of the project is https://www.open-scap.org/tools/scap-workbench/
  
license: GPL-3.0

base: core20
grade: stable
confinement: classic
compression: lzo

apps:
  scap-workbench:
    command: desktop-launch $SNAP/usr/local/bin/scap-workbench
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

parts:
  scap-workbench:
    source: https://github.com/OpenSCAP/scap-workbench
    source-type: git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr/local/bin
      
    build-packages:
      - build-essential 
      - openssh-client 
      - libopenscap-dev 
      - libqt5xmlpatterns5-dev 
      - ssh-askpass
      - asciidoc
      - libpolkit-agent-1-0
      - pkg-config
      
    stage-packages:
      - build-essential 
      - openssh-client 
      - libopenscap-dev 
      - libqt5xmlpatterns5-dev 
      - ssh-askpass
      - asciidoc
      - libpolkit-agent-1-0
      - pkg-config
      - xcb
      - libxcb1-dev
      - qt5dxcb-plugin
      - libxcb-cursor0
      - libx11-xcb1
      - libxau6
      - libxcb-glx0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-render0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-util1
      - libxcb-xfixes0
      - libxdmcp6
      - libxkbcommon-x11-0
      - libxkbcommon0      
      
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
